INSERT into categories (category_name) values ('Digital Cameras');

INSERT into categories (category_name) values ('DSLR Cameras');

INSERT into products (category_id, product_name, price, quantity_remaining, description, image) values ('1', 'Nikon Coolpix L340 Digital Camera, Black','129.99', '115', 'The Nikon L340 is a model that makes capturing beautiful images easy with simple operations. It packs a 28x optical zoom (up to 56x when Dynamic Fine Zoom is used) NIKKOR lens that covers the wide-angle 22.5 mm to super-telephoto 630 mm angles of view (equivalent focal lengths in 35mm [135] format) in one of the smallest bodies in its class. It also offers a large grip that fits easily and comfortably in the hand, simple and intuitive operation, a vibration reduction (VR) function that offers excellent compensation for camera shake, and a large, high-definition LCD monitor.', '<img src="images/nikoncoolpics.jpg" alt="nikon cool pics" />');

INSERT into products (category_id, product_name, price, quantity_remaining, description, image) values ('1', 'Canon PowerShot ELPH 160 20.0MP Digital Camera (Red) + 32GB Card + Reader + Case + Accessory Bundle','124.00', '18', 'High-resolution imaging and HD video recording in a compact package, the Canon PowerShot ELPH 160 Digital Camera is a versatile and convenient point-and-shoot featuring a 20MP 1/2.3" CCD image sensor and DIGIC 4+ image processor, which enables a top sensitivity of ISO 1600 and a 2.2 fps shooting rate. An 8x optical zoom lens provides a 28-224mm equivalent focal length range, which covers wide to tele perspectives for working in a variety of conditions. HD 720/25p video recording is available along with Scene Modes for a creative take on your imagery. Smart AUTO intelligently selects the proper camera settings based on detected scene types and a Help Button can be used to better understand all of the controls and settings of your camera. Besides using the 2.7" 230k-dot LCD monitor for viewing your compositions or playing back imagery, the ELPH 160 is also compatible with the optional Connect Station CS100 for wireless transferring and sharing of your photos and movies.', '<img src="images/canon.jpg" alt="Canon PowerShot ELPH 160 Digital Camera" />');

INSERT into products (category_id, product_name, price, quantity_remaining, description, image) values ('2', 'Sony Alpha a7II Mirrorless Digital Camera - Body Only','1698.00', '17', 'Minimize blur in every shot with the world’s first in-body 5-axis image stabilization in a full-frame camera. Best of all, it works with your favorite lenses. With 24.3MP resolution, super-fast autofocus and a compact design, you’ll capture breathtaking imagery and video that is more stable than ever.', '<img src="images/sonyalpha.jpg" alt="Sony Alpha a7II Mirrorless Digital Camera - Body Only" />');

INSERT into products (category_id, product_name, price, quantity_remaining, description, image) values ('2', 'Nikon D3300 24.2 MP CMOS Digital SLR with Auto Focus-S DX NIKKOR 18-55mm f/3.5-5.6G VR II Zoom Lens (Black)','446.95', '23', 'Capture every special moment in the lifelike quality it deserves--and have a great time doing it! With its included zoom lens, the new ultra-compact AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR II, the D3300 is a small, easy to use HD-SLR. Capture beautiful 24.2-MP photos and 1080p Full HD videos with vibrant colors and softly blurred backgrounds, then share them instantly with your compatible smartphone and the optional WU-1a Wireless Adapter. Whether you"re creating high-resolution panoramas, adding fun special effects or recording dazzling HD video with sound, the D3300 will bring you endless joy, excitement and memories--just like the special moments of your life.', '<img src="images/nikond3300.jpg" alt="Nikon D3300" />');